### ISSUE TITLE
CNPJ is changing and can be alphanumeric (starting July 2026)

### ISSUE THREAD

**Issue by fnando** [fnando/cnpj#16]
https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/cnpj-alfanumerico

**Comment by camilodotto** [comment]
Nando, o código já está suportando totalmente o CNPJ alfa?
Obrigado!

**Comment by fnando** [comment]
@camilodotto yep! Implementado no #15. :)

**Comment by camilodotto** [comment]
@fnando bom dia. Está correto o método aceitar number[] em https://github.com/fnando/cnpj/blob/eebc9977b7de656e7fbeafe57822d3dabd5dfc4d/src/index.ts#L28 ? Não deveria ser string?

**Comment by fnando** [comment]
@camilodotto Nope, é para ser `number[]` mesmo. Essa função está sendo chamada com uma lista de números gerados através de `str.charCodeAt(0) - 48`.

https://github.com/fnando/cnpj/blob/eebc9977b7de656e7fbeafe57822d3dabd5dfc4d/src/index.ts#L111

**Comment by subyster** [comment]
@fnando eu consigo forçar o método `.generate()` a gerar um cnpj numérico apenas?

**Comment by farreltobias** [comment]
> [@fnando](https://github.com/fnando) eu consigo forçar o método `.generate()` a gerar um cnpj numérico apenas?

Apoio poder ter a opção de gerar CNPJs apenas numérico

**Comment by fnando** [comment]
É só fazer pin da versão anterior para ter suporte a geração só com números

**Comment by farreltobias** [comment]
Ah sim, mas se quiser ter suporte para o novo modelo (que virá em julho do ano que vem) e ainda ter a opção de gerar cnpjs numéricos, da pra usar o fallback que criei no PR #17.

Dá uma olhada se faz sentido adicionar, se não, entendo, é só voltar na versão anterior.
